name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Build and Test
      run: |
        dotnet build --configuration Release
        dotnet test --no-restore --verbosity normal

    - name: Publish Console App
      run: |
        dotnet publish -c Release -r win10-x64 src/Michael.Champalet.FeatureMatching.Console/Michael.Champalet.FeatureMatching.Console.csproj
      artifacts:
        name: ConsoleApp
        path: bin/Release/net6.0/win10-x64/publish

    - name: Upload Console App
      uses: actions/upload-artifact@v2
      with:
        name: ConsoleApp
        path: bin/Release/net6.0/win10-x64/publish